type TechIconsType = {
  name: string,
  grayscale: boolean
}[];
export const techIcons: TechIconsType = [
  { grayscale: true, name: 'angular' },
  { grayscale: true, name: 'bootstrap5' },
  { grayscale: true, name: 'css3' },
  { grayscale: true, name: 'html5' },
  { grayscale: true, name: 'js' },
  { grayscale: true, name: 'figma' },
  { grayscale: true, name: 'eslint' },
  { grayscale: true, name: 'git' },
  { grayscale: true, name: 'graphql' },
  { grayscale: true, name: 'headlessui' },
  { grayscale: true, name: 'invision' },
  { grayscale: true, name: 'laravel' },
  { grayscale: true, name: 'less' },
  // { grayscale: true, name: 'markdown' },
  { grayscale: true, name: 'mongodb' },
  { grayscale: true, name: 'nextjs2' },
  { grayscale: true, name: 'nodejs' },
  { grayscale: true, name: 'npm' },
  { grayscale: true, name: 'postgresql' },
  { grayscale: true, name: 'prettier' },
  { grayscale: true, name: 'pwa' },
  { grayscale: true, name: 'reactjs' },
  { grayscale: true, name: 'reactquery' },
  { grayscale: true, name: 'reactrouter' },
  { grayscale: true, name: 'redis' },
  { grayscale: true, name: 'redux' },
  { grayscale: true, name: 'serverless' },
  { grayscale: false, name: 'shadcnui' },
  { grayscale: true, name: 'storybook' },
  { grayscale: true, name: 'tailwindcss' },
  { grayscale: true, name: 'typescript' },
  { grayscale: true, name: 'vitejs' },
  { grayscale: true, name: 'vscode' },
  { grayscale: true, name: 'vuejs' },
  { grayscale: true, name: 'webpack' },
  { grayscale: true, name: 'xd' },
  { grayscale: true, name: 'zod' },
]